GET http://localhost:9191/api/v1/events/1
Accept: application/json

###
POST http://localhost:9191/api/v1/events
Accept: application/json
Content-Type: application/json

{
  "title": "Hello World",
  "startDate": "2023-02-15T18:35:24.00Z"
}

###
PUT http://localhost:9191/api/v1/events/1
Accept: application/json
Content-Type: application/json

{
  "title": "Hello World 1",
  "startDate": "2023-02-15T18:35:24.00Z"
}
