### Create a new event
POST http://localhost:9191/api/v1/events
Accept: application/json
Content-Type: application/json

{
  "title": "Hello World",
  "startDate": "2023-02-15T18:35:24.00Z"
}

### Retrieve event with ID 1
GET http://localhost:9191/api/v1/events/1
Accept: application/json

### Update event with ID 1
PUT http://localhost:9191/api/v1/events/1
Accept: application/json
Content-Type: application/json

{
  "version": 0,
  "title": "Hello World 1",
  "startDate": "2023-02-15T19:35:24.00Z"
}
