spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: root
    password: password

logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
